### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by mmwoods** [mmwoods/project_scope#1]
Markdown
- [x] Fix hour calculation
- [x] Parse markdown into objects
- [x] Save content in local storage
- [ ] Export file
- [ ] Import from GitHub/markdown
- [ ] Export in zip (later)

Rich Text
- [ ] Show preview on xl screen
- [ ] On click slide out animation

Feature Notes
- [ ] Detect certain words
- [ ] Sidebar form (company name, colours, case info)
- [x] Save content in local storage
- [x] Output into HTML
- [x] Apply stylesheet
- [x] Export PDF
- [ ] Export in zip (later)

Tweak Prices
- [ ] Convert into slide out menu
- [ ] Import into snippet menu

Implementation
- [ ] Detect line content/feature notes
- [ ] Import from file/db
- [ ] Align with file
- [ ] Compile into HTML file
- [ ] Export into zip
